### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by amonks** [kevinzweerink/ntype#1]
4d spinning text looks real cool, but I don't care about otf export or live-changing parameters, I'd like to fork this and pare it down into a lil library for simply displaying the text on a webpage, or at least read through what you have and make something similar.

If your intention is for other people to be able to use this code, would you mind adding a license to the project that permits such usage?

If your intention is _not_ to allow that, it makes me sad but I understand. Maybe throw in some "all rights reserved"s to be more clear.

**Comment by kevinzweerink** [comment]
Go for it, I added a standard MIT license. If you want to credit me in your library somehow I'd appreciate it, but either way let me know when you publish it, I'd like to see!

**Comment by kevinzweerink** [comment]
Also happy to answer any questions re: methods or anything like that. I'm not sure how easy my code is to read, so let me know if I can clarify anything for you.

**Comment by amonks** [comment]
Awesome! Thank you. 

I'll let you know if I need anything!
