### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by satishimpingesolutions** [kevinzweerink/ntype#4]
This link doesn't show anything.

[Ntype Blue](http://ntype.blue)

It was working fine earlier but now giving errors. I have used your files in my website and that too stopped working.

Any help?

Satish

**Comment by kevinzweerink** [comment]
Hi Satish,

Everything works fine for me. Could you send me a screenshot of the broken site? Or check the console to see if maybe some files are failing to load?

I am also not sure what you mean about using my files in your website—this isn't really a library or anything that would be particularly useful as a third-party plugin.

Thanks,
Kevin

**Comment by satishimpingesolutions** [comment]
Check these files.

![avenues](https://cloud.githubusercontent.com/assets/7643795/8747353/c12f5fb0-2caf-11e5-85f2-8ae32a1b3134.png)
![ntype](https://cloud.githubusercontent.com/assets/7643795/8747354/c12fef8e-2caf-11e5-9638-7c649b7c48bc.png)

**Comment by satishimpingesolutions** [comment]
2nd screen-shot is of your website.

Thanks,
Satish

**Comment by kevinzweerink** [comment]
Hi Satish,

Those screenshots don't really tell me anything about what could be going wrong or what you are trying to do. 

It could be a browser issue. Ntype.blue should work in new versions of chrome, safari, and firefox, except for the OTF export feature, which only works in chrome. Or you could have javascript disabled, which would definitely break the site.

It seems like what you might be trying to do is use NType as a background for your 'under construction' page. If that's the case, I recommend you check out [@amonks' fork](https://github.com/amonks/mintype) of NType, which is intended to be used in this way. A working demo of that is available at [amonks.github.io/mintype/](http://amonks.github.io/mintype/).

Thanks,
Kevin
